SET SERVEROUTPUT ON
ACCEPT VAR1 PROMPT 'Digite el volumen del tanque';
DECLARE
	VOLUMENBACTERIA NUMBER (18,2);
	VOLUMENTTANQUE NUMBER (18,2);
	BACTERIA NUMBER(18,8) := 0.00016;
	PORCENTAJEBACTERIA NUMBER (18,2);
	PORCENTAJETANQUE1 NUMBER (18,2);
	PORCENTAJETANQUE2 NUMBER (18,2);
	PORCENTAJETANQUE3 NUMBER (18,2);
	CONTAMINACION  NUMBER(18,2) := 0;
	AGUA NUMBER(18,0) := 0;
	MINU NUMBER (18,0) := 0;
BEGIN
	VOLUMENTTANQUE := &VAR1;
	VOLUMENBACTERIA := VOLUMENTTANQUE * BACTERIA;
	PORCENTAJEBACTERIA := (VOLUMENBACTERIA * 100) / VOLUMENTTANQUE;
	PORCENTAJETANQUE1 := VOLUMENTTANQUE * 0.35;
	PORCENTAJETANQUE2 := VOLUMENTTANQUE * 0.50;
	PORCENTAJETANQUE3 := VOLUMENTTANQUE * 0.1;

	WHILE  CONTAMINACION <= PORCENTAJETANQUE2 LOOP
		MINU := MINU + 1;
		AGUA := AGUA + 100;
		CONTAMINACION := CONTAMINACION + VOLUMENBACTERIA;
	END LOOP;
	IF (CONTAMINACION <= PORCENTAJETANQUE3)THEN
		DBMS_OUTPUT.PUT_LINE('Contaminacion permitida');
	END IF;

	IF (CONTAMINACION >= PORCENTAJETANQUE1)THEN
		DBMS_OUTPUT.PUT_LINE('Contaminacion excesiva, se cierran las compuertas de vaciado');
	END IF;
END;